# Generated by Django 3.2.9 on 2021-11-04 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['-date_created'], 'verbose_name_plural': 'Cities'},
        ),
    ]
