# Generated by Django 3.2.9 on 2021-11-05 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20211105_0525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='location',
            name='image_url',
        ),
        migrations.AddField(
            model_name='city',
            name='picture',
            field=models.ImageField(default='default.jpg', upload_to='picture/'),
        ),
        migrations.AddField(
            model_name='location',
            name='picture',
            field=models.ImageField(default='default.jpg', upload_to='picture/'),
        ),
        migrations.AlterField(
            model_name='location',
            name='title',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
