# Generated by Django 3.2.9 on 2021-11-11 08:56

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20211105_0655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='picture',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.ImageField(default='default.jpg', upload_to='staticfiles/picture/'), size=None),
        ),
    ]
