# Generated by Django 3.2.9 on 2021-11-12 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_city_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='price',
        ),
        migrations.RemoveField(
            model_name='location',
            name='status',
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=155, unique=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='picture',
            field=models.ImageField(default='default.jpg', upload_to='staticfiles/picture/'),
        ),
        migrations.AlterField(
            model_name='location',
            name='title',
            field=models.CharField(max_length=150),
        ),
    ]
