# Generated by Django 3.2.9 on 2021-11-27 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20211112_0923'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='location',
            name='picture',
            field=models.ImageField(default='picture/default.jpg', upload_to='picture/'),
        ),
    ]
