# Generated by Django 3.2.9 on 2021-11-27 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20211127_0754'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='comment',
            field=models.TextField(null=True),
        ),
    ]
