# Generated by Django 3.2.9 on 2021-11-28 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_location_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='City',
        ),
    ]
