# Generated by Django 3.2.9 on 2021-11-28 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_user_phone_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
