# Generated by Django 3.2.9 on 2021-11-28 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='picture',
            field=models.ImageField(default='picture/default.jpg', max_length=200, upload_to='picture/'),
        ),
    ]
